spring.application.name=pertemuan11

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/praktikum_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:praktikum_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html